[package]
name = "rust-mimiio"
version = "0.1.0"
authors = ["emergent <yosikawa@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.33.0"
futures = "0.1.27"
tokio = "0.1.20"
websocket = "0.22.4"


